//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Califica
    {
        public string Cod_Cali { get; set; }
        public string Cod_P { get; set; }
        public string Cod_Niño { get; set; }
        public string Observaciones { get; set; }
        public string Mes { get; set; }
    
        public virtual Niños Niños { get; set; }
        public virtual profesores profesores { get; set; }
    }
}
