//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.Niños = new HashSet<Niños>();
            this.profesores = new HashSet<profesores>();
        }
    
        public string Codigo_Curso { get; set; }
        public string Horario_Desayuno { get; set; }
        public string Horario_Actividades { get; set; }
        public string Horario_Almuerzos { get; set; }
        public string Horario_Descanso { get; set; }
        public string Horario_Juego { get; set; }
        public Nullable<int> Cantidad_Niños { get; set; }
        public Nullable<System.DateTime> Gestion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Niños> Niños { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profesores> profesores { get; set; }
    }
}
