//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Guarderia_BamBamEntitiess : DbContext
    {
        public Guarderia_BamBamEntitiess()
            : base("name=Guarderia_BamBamEntitiess")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividades> Actividades { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Califica> Califica { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Niños> Niños { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<profesores> profesores { get; set; }
        public virtual DbSet<Re_Inscripcion> Re_Inscripcion { get; set; }
        public virtual DbSet<Secretarios> Secretarios { get; set; }
        public virtual DbSet<Solicitud_Actividad> Solicitud_Actividad { get; set; }
        public virtual DbSet<Solicitud_Permisos> Solicitud_Permisos { get; set; }
        public virtual DbSet<Tutor> Tutor { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
