//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Niños
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Niños()
        {
            this.Califica = new HashSet<Califica>();
            this.Solicitud_Permisos = new HashSet<Solicitud_Permisos>();
        }
    
        public string Cod_Niño { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string Genero { get; set; }
        public string Fecha_Nac { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> Altura { get; set; }
        public Nullable<bool> Vacunas { get; set; }
        public string Discapacidad { get; set; }
        public string Tutor { get; set; }
        public string Curso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Califica> Califica { get; set; }
        public virtual Curso Curso1 { get; set; }
        public virtual Tutor Tutor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud_Permisos> Solicitud_Permisos { get; set; }
    }
}
